//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceTipo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTipo.ISTipo")]
    public interface ISTipo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISTipo/SelectById", ReplyAction="http://tempuri.org/ISTipo/SelectByIdResponse")]
        AIPos.Domain.Tipo SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISTipo/SelectById", ReplyAction="http://tempuri.org/ISTipo/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Tipo> SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISTipo/SelectAll", ReplyAction="http://tempuri.org/ISTipo/SelectAllResponse")]
        AIPos.Domain.Tipo[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISTipo/SelectAll", ReplyAction="http://tempuri.org/ISTipo/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Tipo[]> SelectAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISTipoChannel : AIPos.DekstopLayer.ServiceTipo.ISTipo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STipoClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceTipo.ISTipo>, AIPos.DekstopLayer.ServiceTipo.ISTipo {
        
        public STipoClient() {
        }
        
        public STipoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public STipoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STipoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STipoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Tipo SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Tipo> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
        
        public AIPos.Domain.Tipo[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Tipo[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
    }
}
