//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceListaPrecioProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceListaPrecioProducto.IISListaPrecioProducto")]
    public interface IISListaPrecioProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoSucursal", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoSucursalResponse")]
        AIPos.Domain.ListaPrecioProducto SelectByProductoSucursal(int SucursalId, int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoSucursal", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoSucursalResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoSucursalAsync(int SucursalId, int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoCliente", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoClienteResponse")]
        AIPos.Domain.ListaPrecioProducto SelectByProductoCliente(int ClienteId, int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoCliente", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoClienteResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoClienteAsync(int ClienteId, int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoLista", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoListaResponse")]
        AIPos.Domain.ListaPrecioProducto SelectByProductoLista(int ListaId, int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISListaPrecioProducto/SelectByProductoLista", ReplyAction="http://tempuri.org/IISListaPrecioProducto/SelectByProductoListaResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoListaAsync(int ListaId, int ProductoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IISListaPrecioProductoChannel : AIPos.DekstopLayer.ServiceListaPrecioProducto.IISListaPrecioProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ISListaPrecioProductoClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceListaPrecioProducto.IISListaPrecioProducto>, AIPos.DekstopLayer.ServiceListaPrecioProducto.IISListaPrecioProducto {
        
        public ISListaPrecioProductoClient() {
        }
        
        public ISListaPrecioProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ISListaPrecioProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISListaPrecioProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISListaPrecioProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.ListaPrecioProducto SelectByProductoSucursal(int SucursalId, int ProductoId) {
            return base.Channel.SelectByProductoSucursal(SucursalId, ProductoId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoSucursalAsync(int SucursalId, int ProductoId) {
            return base.Channel.SelectByProductoSucursalAsync(SucursalId, ProductoId);
        }
        
        public AIPos.Domain.ListaPrecioProducto SelectByProductoCliente(int ClienteId, int ProductoId) {
            return base.Channel.SelectByProductoCliente(ClienteId, ProductoId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoClienteAsync(int ClienteId, int ProductoId) {
            return base.Channel.SelectByProductoClienteAsync(ClienteId, ProductoId);
        }
        
        public AIPos.Domain.ListaPrecioProducto SelectByProductoLista(int ListaId, int ProductoId) {
            return base.Channel.SelectByProductoLista(ListaId, ProductoId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ListaPrecioProducto> SelectByProductoListaAsync(int ListaId, int ProductoId) {
            return base.Channel.SelectByProductoListaAsync(ListaId, ProductoId);
        }
    }
}
