//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVenta.IISVenta")]
    public interface IISVenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/Insert", ReplyAction="http://tempuri.org/IISVenta/InsertResponse")]
        AIPos.Domain.Venta Insert(AIPos.Domain.Venta venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/Insert", ReplyAction="http://tempuri.org/IISVenta/InsertResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Venta> InsertAsync(AIPos.Domain.Venta venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioVenta", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioVentaResponse")]
        int GenerarFolioVenta(int SucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioVenta", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioVentaResponse")]
        System.Threading.Tasks.Task<int> GenerarFolioVentaAsync(int SucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCancelado", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoResponse")]
        int GenerarFolioCancelado(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCancelado", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoResponse")]
        System.Threading.Tasks.Task<int> GenerarFolioCanceladoAsync(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoApartado", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoApartadoResponse")]
        int GenerarFolioCanceladoApartado(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoApartado", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoApartadoResponse")]
        System.Threading.Tasks.Task<int> GenerarFolioCanceladoApartadoAsync(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoDomicilio", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoDomicilioResponse")]
        int GenerarFolioCanceladoDomicilio(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoDomicilio", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoDomicilioResponse")]
        System.Threading.Tasks.Task<int> GenerarFolioCanceladoDomicilioAsync(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoServicio", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoServicioResponse")]
        int GenerarFolioCanceladoServicio(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/GenerarFolioCanceladoServicio", ReplyAction="http://tempuri.org/IISVenta/GenerarFolioCanceladoServicioResponse")]
        System.Threading.Tasks.Task<int> GenerarFolioCanceladoServicioAsync(int SucursalId, long Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/RecuperarCorteCaja", ReplyAction="http://tempuri.org/IISVenta/RecuperarCorteCajaResponse")]
        AIPos.Domain.ReporteCorteCaja[] RecuperarCorteCaja(long FechaInicio, long FechaFin, System.Nullable<int> SucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/RecuperarCorteCaja", ReplyAction="http://tempuri.org/IISVenta/RecuperarCorteCajaResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ReporteCorteCaja[]> RecuperarCorteCajaAsync(long FechaInicio, long FechaFin, System.Nullable<int> SucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/RecuperarVentaDetalle", ReplyAction="http://tempuri.org/IISVenta/RecuperarVentaDetalleResponse")]
        AIPos.Domain.VentaDetalle[] RecuperarVentaDetalle(int VentaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISVenta/RecuperarVentaDetalle", ReplyAction="http://tempuri.org/IISVenta/RecuperarVentaDetalleResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.VentaDetalle[]> RecuperarVentaDetalleAsync(int VentaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IISVentaChannel : AIPos.DekstopLayer.ServiceVenta.IISVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ISVentaClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceVenta.IISVenta>, AIPos.DekstopLayer.ServiceVenta.IISVenta {
        
        public ISVentaClient() {
        }
        
        public ISVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ISVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Venta Insert(AIPos.Domain.Venta venta) {
            return base.Channel.Insert(venta);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Venta> InsertAsync(AIPos.Domain.Venta venta) {
            return base.Channel.InsertAsync(venta);
        }
        
        public int GenerarFolioVenta(int SucursalId) {
            return base.Channel.GenerarFolioVenta(SucursalId);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFolioVentaAsync(int SucursalId) {
            return base.Channel.GenerarFolioVentaAsync(SucursalId);
        }
        
        public int GenerarFolioCancelado(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCancelado(SucursalId, Fecha);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFolioCanceladoAsync(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoAsync(SucursalId, Fecha);
        }
        
        public int GenerarFolioCanceladoApartado(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoApartado(SucursalId, Fecha);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFolioCanceladoApartadoAsync(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoApartadoAsync(SucursalId, Fecha);
        }
        
        public int GenerarFolioCanceladoDomicilio(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoDomicilio(SucursalId, Fecha);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFolioCanceladoDomicilioAsync(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoDomicilioAsync(SucursalId, Fecha);
        }
        
        public int GenerarFolioCanceladoServicio(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoServicio(SucursalId, Fecha);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFolioCanceladoServicioAsync(int SucursalId, long Fecha) {
            return base.Channel.GenerarFolioCanceladoServicioAsync(SucursalId, Fecha);
        }
        
        public AIPos.Domain.ReporteCorteCaja[] RecuperarCorteCaja(long FechaInicio, long FechaFin, System.Nullable<int> SucursalId) {
            return base.Channel.RecuperarCorteCaja(FechaInicio, FechaFin, SucursalId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ReporteCorteCaja[]> RecuperarCorteCajaAsync(long FechaInicio, long FechaFin, System.Nullable<int> SucursalId) {
            return base.Channel.RecuperarCorteCajaAsync(FechaInicio, FechaFin, SucursalId);
        }
        
        public AIPos.Domain.VentaDetalle[] RecuperarVentaDetalle(int VentaId) {
            return base.Channel.RecuperarVentaDetalle(VentaId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.VentaDetalle[]> RecuperarVentaDetalleAsync(int VentaId) {
            return base.Channel.RecuperarVentaDetalleAsync(VentaId);
        }
    }
}
