//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServicePedidoSucursal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePedidoSucursal.ISPedidoSucursal")]
    public interface ISPedidoSucursal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Insert", ReplyAction="http://tempuri.org/ISPedidoSucursal/InsertResponse")]
        AIPos.Domain.PedidoSucursal Insert(AIPos.Domain.PedidoSucursal entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Insert", ReplyAction="http://tempuri.org/ISPedidoSucursal/InsertResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal> InsertAsync(AIPos.Domain.PedidoSucursal entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Update", ReplyAction="http://tempuri.org/ISPedidoSucursal/UpdateResponse")]
        AIPos.Domain.PedidoSucursal Update(AIPos.Domain.PedidoSucursal entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Update", ReplyAction="http://tempuri.org/ISPedidoSucursal/UpdateResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal> UpdateAsync(AIPos.Domain.PedidoSucursal entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Delete", ReplyAction="http://tempuri.org/ISPedidoSucursal/DeleteResponse")]
        void Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/Delete", ReplyAction="http://tempuri.org/ISPedidoSucursal/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/SelectBySucursalFecha", ReplyAction="http://tempuri.org/ISPedidoSucursal/SelectBySucursalFechaResponse")]
        AIPos.Domain.PedidoSucursal[] SelectBySucursalFecha(int SucursalId, long Day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPedidoSucursal/SelectBySucursalFecha", ReplyAction="http://tempuri.org/ISPedidoSucursal/SelectBySucursalFechaResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal[]> SelectBySucursalFechaAsync(int SucursalId, long Day);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISPedidoSucursalChannel : AIPos.DekstopLayer.ServicePedidoSucursal.ISPedidoSucursal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPedidoSucursalClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServicePedidoSucursal.ISPedidoSucursal>, AIPos.DekstopLayer.ServicePedidoSucursal.ISPedidoSucursal {
        
        public SPedidoSucursalClient() {
        }
        
        public SPedidoSucursalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPedidoSucursalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPedidoSucursalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPedidoSucursalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.PedidoSucursal Insert(AIPos.Domain.PedidoSucursal entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal> InsertAsync(AIPos.Domain.PedidoSucursal entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public AIPos.Domain.PedidoSucursal Update(AIPos.Domain.PedidoSucursal entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal> UpdateAsync(AIPos.Domain.PedidoSucursal entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(int Id) {
            base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
        
        public AIPos.Domain.PedidoSucursal[] SelectBySucursalFecha(int SucursalId, long Day) {
            return base.Channel.SelectBySucursalFecha(SucursalId, Day);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.PedidoSucursal[]> SelectBySucursalFechaAsync(int SucursalId, long Day) {
            return base.Channel.SelectBySucursalFechaAsync(SucursalId, Day);
        }
    }
}
