//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceEstatusServicioApartado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstatusServicioApartado.ISEstatusServicioApartado")]
    public interface ISEstatusServicioApartado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEstatusServicioApartado/SelectAll", ReplyAction="http://tempuri.org/ISEstatusServicioApartado/SelectAllResponse")]
        AIPos.Domain.EstatusServicioApartado[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEstatusServicioApartado/SelectAll", ReplyAction="http://tempuri.org/ISEstatusServicioApartado/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.EstatusServicioApartado[]> SelectAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISEstatusServicioApartadoChannel : AIPos.DekstopLayer.ServiceEstatusServicioApartado.ISEstatusServicioApartado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SEstatusServicioApartadoClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceEstatusServicioApartado.ISEstatusServicioApartado>, AIPos.DekstopLayer.ServiceEstatusServicioApartado.ISEstatusServicioApartado {
        
        public SEstatusServicioApartadoClient() {
        }
        
        public SEstatusServicioApartadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SEstatusServicioApartadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEstatusServicioApartadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEstatusServicioApartadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.EstatusServicioApartado[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.EstatusServicioApartado[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
    }
}
