//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceSucursal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSucursal.ISSucursal")]
    public interface ISSucursal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSucursal/SelectAll", ReplyAction="http://tempuri.org/ISSucursal/SelectAllResponse")]
        AIPos.Domain.Sucursal[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSucursal/SelectAll", ReplyAction="http://tempuri.org/ISSucursal/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Sucursal[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSucursal/SelectById", ReplyAction="http://tempuri.org/ISSucursal/SelectByIdResponse")]
        AIPos.Domain.Sucursal SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSucursal/SelectById", ReplyAction="http://tempuri.org/ISSucursal/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Sucursal> SelectByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISSucursalChannel : AIPos.DekstopLayer.ServiceSucursal.ISSucursal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSucursalClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceSucursal.ISSucursal>, AIPos.DekstopLayer.ServiceSucursal.ISSucursal {
        
        public SSucursalClient() {
        }
        
        public SSucursalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSucursalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSucursalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSucursalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Sucursal[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Sucursal[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public AIPos.Domain.Sucursal SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Sucursal> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
    }
}
