//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceUnidad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUnidad.ISUnidad")]
    public interface ISUnidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUnidad/SelectById", ReplyAction="http://tempuri.org/ISUnidad/SelectByIdResponse")]
        AIPos.Domain.Unidad SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUnidad/SelectById", ReplyAction="http://tempuri.org/ISUnidad/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Unidad> SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUnidad/SelectAll", ReplyAction="http://tempuri.org/ISUnidad/SelectAllResponse")]
        AIPos.Domain.Unidad[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUnidad/SelectAll", ReplyAction="http://tempuri.org/ISUnidad/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Unidad[]> SelectAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISUnidadChannel : AIPos.DekstopLayer.ServiceUnidad.ISUnidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SUnidadClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceUnidad.ISUnidad>, AIPos.DekstopLayer.ServiceUnidad.ISUnidad {
        
        public SUnidadClient() {
        }
        
        public SUnidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SUnidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUnidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUnidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Unidad SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Unidad> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
        
        public AIPos.Domain.Unidad[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Unidad[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
    }
}
