//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceSeguimientoServicioApartado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSeguimientoServicioApartado.ISSeguimientoServicioApartado")]
    public interface ISSeguimientoServicioApartado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/Insert", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/InsertResponse")]
        AIPos.Domain.SeguimientoServicioApartado Insert(AIPos.Domain.SeguimientoServicioApartado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/Insert", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/InsertResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> InsertAsync(AIPos.Domain.SeguimientoServicioApartado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/Update", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/UpdateResponse")]
        AIPos.Domain.SeguimientoServicioApartado Update(AIPos.Domain.SeguimientoServicioApartado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/Update", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/UpdateResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> UpdateAsync(AIPos.Domain.SeguimientoServicioApartado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/SelectById", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/SelectByIdResponse")]
        AIPos.Domain.SeguimientoServicioApartado SelectById(int VentaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSeguimientoServicioApartado/SelectById", ReplyAction="http://tempuri.org/ISSeguimientoServicioApartado/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> SelectByIdAsync(int VentaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISSeguimientoServicioApartadoChannel : AIPos.DekstopLayer.ServiceSeguimientoServicioApartado.ISSeguimientoServicioApartado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSeguimientoServicioApartadoClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceSeguimientoServicioApartado.ISSeguimientoServicioApartado>, AIPos.DekstopLayer.ServiceSeguimientoServicioApartado.ISSeguimientoServicioApartado {
        
        public SSeguimientoServicioApartadoClient() {
        }
        
        public SSeguimientoServicioApartadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSeguimientoServicioApartadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSeguimientoServicioApartadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSeguimientoServicioApartadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.SeguimientoServicioApartado Insert(AIPos.Domain.SeguimientoServicioApartado entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> InsertAsync(AIPos.Domain.SeguimientoServicioApartado entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public AIPos.Domain.SeguimientoServicioApartado Update(AIPos.Domain.SeguimientoServicioApartado entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> UpdateAsync(AIPos.Domain.SeguimientoServicioApartado entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public AIPos.Domain.SeguimientoServicioApartado SelectById(int VentaId) {
            return base.Channel.SelectById(VentaId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.SeguimientoServicioApartado> SelectByIdAsync(int VentaId) {
            return base.Channel.SelectByIdAsync(VentaId);
        }
    }
}
