//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceListaPrecio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceListaPrecio.ISListaPrecio")]
    public interface ISListaPrecio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISListaPrecio/SelectAll", ReplyAction="http://tempuri.org/ISListaPrecio/SelectAllResponse")]
        AIPos.Domain.ListaPrecio[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISListaPrecio/SelectAll", ReplyAction="http://tempuri.org/ISListaPrecio/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ListaPrecio[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISListaPrecio/RecuperarListaPrecioDeSucursal", ReplyAction="http://tempuri.org/ISListaPrecio/RecuperarListaPrecioDeSucursalResponse")]
        AIPos.Domain.ListaPrecio RecuperarListaPrecioDeSucursal(int SucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISListaPrecio/RecuperarListaPrecioDeSucursal", ReplyAction="http://tempuri.org/ISListaPrecio/RecuperarListaPrecioDeSucursalResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ListaPrecio> RecuperarListaPrecioDeSucursalAsync(int SucursalId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISListaPrecioChannel : AIPos.DekstopLayer.ServiceListaPrecio.ISListaPrecio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SListaPrecioClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceListaPrecio.ISListaPrecio>, AIPos.DekstopLayer.ServiceListaPrecio.ISListaPrecio {
        
        public SListaPrecioClient() {
        }
        
        public SListaPrecioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SListaPrecioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SListaPrecioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SListaPrecioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.ListaPrecio[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ListaPrecio[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public AIPos.Domain.ListaPrecio RecuperarListaPrecioDeSucursal(int SucursalId) {
            return base.Channel.RecuperarListaPrecioDeSucursal(SucursalId);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ListaPrecio> RecuperarListaPrecioDeSucursalAsync(int SucursalId) {
            return base.Channel.RecuperarListaPrecioDeSucursalAsync(SucursalId);
        }
    }
}
