//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProveedor.ISProveedor")]
    public interface ISProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectAll", ReplyAction="http://tempuri.org/ISProveedor/SelectAllResponse")]
        AIPos.Domain.Proveedor[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectAll", ReplyAction="http://tempuri.org/ISProveedor/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Proveedor[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectByCodigo", ReplyAction="http://tempuri.org/ISProveedor/SelectByCodigoResponse")]
        AIPos.Domain.Proveedor SelectByCodigo(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectByCodigo", ReplyAction="http://tempuri.org/ISProveedor/SelectByCodigoResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Proveedor> SelectByCodigoAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectById", ReplyAction="http://tempuri.org/ISProveedor/SelectByIdResponse")]
        AIPos.Domain.Proveedor SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProveedor/SelectById", ReplyAction="http://tempuri.org/ISProveedor/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Proveedor> SelectByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISProveedorChannel : AIPos.DekstopLayer.ServiceProveedor.ISProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SProveedorClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceProveedor.ISProveedor>, AIPos.DekstopLayer.ServiceProveedor.ISProveedor {
        
        public SProveedorClient() {
        }
        
        public SProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Proveedor[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Proveedor[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public AIPos.Domain.Proveedor SelectByCodigo(string Codigo) {
            return base.Channel.SelectByCodigo(Codigo);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Proveedor> SelectByCodigoAsync(string Codigo) {
            return base.Channel.SelectByCodigoAsync(Codigo);
        }
        
        public AIPos.Domain.Proveedor SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Proveedor> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
    }
}
