//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.ISProducto")]
    public interface ISProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectAllProductos", ReplyAction="http://tempuri.org/ISProducto/SelectAllProductosResponse")]
        AIPos.Domain.Producto[] SelectAllProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectAllProductos", ReplyAction="http://tempuri.org/ISProducto/SelectAllProductosResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Producto[]> SelectAllProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectByCodigo", ReplyAction="http://tempuri.org/ISProducto/SelectByCodigoResponse")]
        AIPos.Domain.Producto SelectByCodigo(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectByCodigo", ReplyAction="http://tempuri.org/ISProducto/SelectByCodigoResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Producto> SelectByCodigoAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectById", ReplyAction="http://tempuri.org/ISProducto/SelectByIdResponse")]
        AIPos.Domain.Producto SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISProducto/SelectById", ReplyAction="http://tempuri.org/ISProducto/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Producto> SelectByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISProductoChannel : AIPos.DekstopLayer.ServiceProducto.ISProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SProductoClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceProducto.ISProducto>, AIPos.DekstopLayer.ServiceProducto.ISProducto {
        
        public SProductoClient() {
        }
        
        public SProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Producto[] SelectAllProductos() {
            return base.Channel.SelectAllProductos();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Producto[]> SelectAllProductosAsync() {
            return base.Channel.SelectAllProductosAsync();
        }
        
        public AIPos.Domain.Producto SelectByCodigo(string Codigo) {
            return base.Channel.SelectByCodigo(Codigo);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Producto> SelectByCodigoAsync(string Codigo) {
            return base.Channel.SelectByCodigoAsync(Codigo);
        }
        
        public AIPos.Domain.Producto SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Producto> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
    }
}
