//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceConfiguracion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConfiguracion.ISConfiguracionGeneral")]
    public interface ISConfiguracionGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISConfiguracionGeneral/RecuperarConfiguracion", ReplyAction="http://tempuri.org/ISConfiguracionGeneral/RecuperarConfiguracionResponse")]
        AIPos.Domain.ConfiguracionGeneral RecuperarConfiguracion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISConfiguracionGeneral/RecuperarConfiguracion", ReplyAction="http://tempuri.org/ISConfiguracionGeneral/RecuperarConfiguracionResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.ConfiguracionGeneral> RecuperarConfiguracionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISConfiguracionGeneralChannel : AIPos.DekstopLayer.ServiceConfiguracion.ISConfiguracionGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SConfiguracionGeneralClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceConfiguracion.ISConfiguracionGeneral>, AIPos.DekstopLayer.ServiceConfiguracion.ISConfiguracionGeneral {
        
        public SConfiguracionGeneralClient() {
        }
        
        public SConfiguracionGeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SConfiguracionGeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SConfiguracionGeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SConfiguracionGeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.ConfiguracionGeneral RecuperarConfiguracion() {
            return base.Channel.RecuperarConfiguracion();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.ConfiguracionGeneral> RecuperarConfiguracionAsync() {
            return base.Channel.RecuperarConfiguracionAsync();
        }
    }
}
