//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPos.DekstopLayer.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.ISUsuario")]
    public interface ISUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/Login", ReplyAction="http://tempuri.org/ISUsuario/LoginResponse")]
        AIPos.Domain.Usuario Login(string Username, string Password, int Sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/Login", ReplyAction="http://tempuri.org/ISUsuario/LoginResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Usuario> LoginAsync(string Username, string Password, int Sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/SelectById", ReplyAction="http://tempuri.org/ISUsuario/SelectByIdResponse")]
        AIPos.Domain.Usuario SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/SelectById", ReplyAction="http://tempuri.org/ISUsuario/SelectByIdResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Usuario> SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/SelectAll", ReplyAction="http://tempuri.org/ISUsuario/SelectAllResponse")]
        AIPos.Domain.Usuario[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISUsuario/SelectAll", ReplyAction="http://tempuri.org/ISUsuario/SelectAllResponse")]
        System.Threading.Tasks.Task<AIPos.Domain.Usuario[]> SelectAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISUsuarioChannel : AIPos.DekstopLayer.ServiceUsuario.ISUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SUsuarioClient : System.ServiceModel.ClientBase<AIPos.DekstopLayer.ServiceUsuario.ISUsuario>, AIPos.DekstopLayer.ServiceUsuario.ISUsuario {
        
        public SUsuarioClient() {
        }
        
        public SUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIPos.Domain.Usuario Login(string Username, string Password, int Sucursal) {
            return base.Channel.Login(Username, Password, Sucursal);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Usuario> LoginAsync(string Username, string Password, int Sucursal) {
            return base.Channel.LoginAsync(Username, Password, Sucursal);
        }
        
        public AIPos.Domain.Usuario SelectById(int Id) {
            return base.Channel.SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Usuario> SelectByIdAsync(int Id) {
            return base.Channel.SelectByIdAsync(Id);
        }
        
        public AIPos.Domain.Usuario[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<AIPos.Domain.Usuario[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
    }
}
